use_gpu: True
device: 0
early_stop:
  patience: 0
federate:
  mode: standalone
  client_num: 3
  total_round_num: 100
  save_to: "mezo_testcase_full.ckpt"
  save_freq: 50
  share_local_model: True
  online_aggr: False
data:
  root: data/
  type: 'alpaca@llm'
  splits: [0.98,0.01,0.01]
  splitter: 'iid'
llm:
  tok_len: 1000
  chat:
    max_len: 2000
  # Disable adapter for full-parameter fine-tuning
  adapter:
    use: False
    args: []
dataloader:
  batch_size: 1
model:
  type: 'openlm-research/open_llama_3b_v2@huggingface_llm'
train:
  # Change strategy from 'frozen' to 'finetune'
  train_strategy: 'finetune'
  local_update_steps: 5
  batch_or_epoch: batch
  optimizer:
    lr: 0.00001
    weight_decay: 0.0
  is_enable_half: False
criterion:
  type: CrossEntropyLoss
trainer:
  type: mezotrainer
eval:
  freq: 10
  metrics: ['loss']
  count_flops: False
